//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElClima.ApplicationServices.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElClima.ApplicationServices.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;LocalidadId&quot;: &quot;1&quot;,
        ///		&quot;nombre&quot;: &quot;A. A. Fernandez&quot;,
        ///		&quot;IdProvincia&quot;: &quot;1&quot;,
        ///		&quot;codigoPostal&quot;: &quot;1825&quot;
        ///	},
        ///	{
        ///		&quot;LocalidadId&quot;: &quot;2&quot;,
        ///		&quot;nombre&quot;: &quot;Abasto&quot;,
        ///		&quot;IdProvincia&quot;: &quot;1&quot;,
        ///		&quot;codigoPostal&quot;: &quot;1903&quot;
        ///	},
        ///	{
        ///		&quot;LocalidadId&quot;: &quot;3&quot;,
        ///		&quot;nombre&quot;: &quot;Abbott&quot;,
        ///		&quot;IdProvincia&quot;: &quot;1&quot;,
        ///		&quot;codigoPostal&quot;: &quot;7228&quot;
        ///	},
        ///	{
        ///		&quot;LocalidadId&quot;: &quot;4&quot;,
        ///		&quot;nombre&quot;: &quot;Abel&quot;,
        ///		&quot;IdProvincia&quot;: &quot;1&quot;,
        ///		&quot;codigoPostal&quot;: &quot;6450&quot;
        ///	},
        ///	{
        ///		&quot;LocalidadId&quot;: &quot;5&quot;,
        ///		&quot;nombre&quot;: &quot;Acassuso&quot;,
        ///		&quot;IdProvincia&quot;: &quot;1&quot;,
        ///		&quot;codigoPostal&quot;: &quot;1640&quot;
        ///	},
        ///	{
        ///		&quot;Local [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string localidades_json {
            get {
                return ResourceManager.GetString("localidades_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;provinciaId&quot;: &quot;1&quot;,
        ///		&quot;nombre&quot;: &quot;Buenos Aires&quot; 
        ///	},
        ///	{
        ///		&quot;provinciaId&quot;: &quot;2&quot;,
        ///		&quot;nombre&quot;: &quot;Catamarca&quot; 
        ///	},
        ///	{
        ///		&quot;provinciaId&quot;: &quot;3&quot;,
        ///		&quot;nombre&quot;: &quot;Cordoba&quot; 
        ///	},
        ///	{
        ///		&quot;provinciaId&quot;: &quot;4&quot;,
        ///		&quot;nombre&quot;: &quot;Corrientes&quot; 
        ///	},
        ///	{
        ///		&quot;provinciaId&quot;: &quot;5&quot;,
        ///		&quot;nombre&quot;: &quot;Chaco&quot; 
        ///	},
        ///	{
        ///		&quot;provinciaId&quot;: &quot;6&quot;,
        ///		&quot;nombre&quot;: &quot;Chubut&quot; 
        ///	},
        ///	{
        ///		&quot;provinciaId&quot;: &quot;7&quot;,
        ///		&quot;nombre&quot;: &quot;Entre Rios&quot; 
        ///	},
        ///	{
        ///		&quot;provinciaId&quot;: &quot;8&quot;,
        ///		&quot;nombre&quot;: &quot;Formosa&quot; 
        ///	},
        ///	{
        ///		&quot;provinciaId&quot;: &quot;9&quot;,
        ///		&quot;nombre&quot;: &quot;Jujuy&quot; 
        ///	},
        ///	{
        ///		&quot;provinciaId&quot;: &quot;10&quot;,
        ///		&quot;nombr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string provincias_json {
            get {
                return ResourceManager.GetString("provincias_json", resourceCulture);
            }
        }
    }
}
